{% set version = "4041.97" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-fbasics
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/fBasics_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/fBasics/fBasics_{{ version }}.tar.gz
  sha256: 9942055e06e892e00616fa96255977c8bd7622666d4890b259e89f3ac74915ab

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - cross-r-base {{ r_base }}  # [build_platform != target_platform]
    - r-gss                      # [build_platform != target_platform]
    - r-mass                     # [build_platform != target_platform]
    - r-spatial                  # [build_platform != target_platform]
    - r-stabledist               # [build_platform != target_platform]
    - r-timedate                 # [build_platform != target_platform]
    - r-timeseries               # [build_platform != target_platform]
    - {{ compiler('c') }}        # [not win]
    - {{ stdlib("c") }}          # [not win]
    - {{ compiler('m2w64_c') }}  # [win]
    - {{ stdlib("m2w64_c") }}    # [win]
    - {{ posix }}filesystem      # [win]
    - {{ posix }}make
    - {{ posix }}sed             # [win]
    - {{ posix }}coreutils       # [win]
    - {{ posix }}zip             # [win]
  host:
    - r-base
    - r-gss
    - r-mass
    - r-spatial
    - r-stabledist
    - r-timedate
    - r-timeseries
  run:
    - r-base
    - r-gss
    - r-mass
    - r-spatial
    - r-stabledist
    - r-timedate
    - r-timeseries

test:
  commands:
    - $R -e "library('fBasics')"           # [not win]
    - "\"%R%\" -e \"library('fBasics')\""  # [win]

about:
  home: https://www.rmetrics.org
  dev_url: https://r-forge.r-project.org/scm/viewvc.php/pkg/fBasics/?root=rmetrics
  doc_url: https://geobosh.github.io/fBasicsDoc/
  license: GPL-2.0-or-later
  summary: Provides a collection of functions to  explore and to investigate basic properties of financial returns and related quantities. The covered fields include techniques of explorative data analysis and the investigation of distributional properties, including parameter estimation and hypothesis testing. Even more
    there are several utility functions for data handling and management.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
