{% set version = "3042.89.2" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-fbasics
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/fBasics_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/fBasics/fBasics_{{ version }}.tar.gz
  sha256: d69ddadaa96b3b77e5573d82df40d63db883297cedc9e622294c041ef944af5d

build:
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-mass
    - r-gss
    - r-spatial
    - r-stabledist
    - r-timedate
    - r-timeseries
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-mass
    - r-gss
    - r-spatial
    - r-stabledist
    - r-timedate
    - r-timeseries

test:
  commands:
    - $R -e "library('fBasics')"           # [not win]
    - "\"%R%\" -e \"library('fBasics')\""  # [win]

about:
  home: https://www.rmetrics.org
  license: GPL-2.0-or-later
  summary: Provides a collection of functions to  explore and to investigate basic properties of financial returns  and related quantities. The covered fields include techniques of explorative data analysis and the investigation of distributional properties, including parameter estimation and hypothesis testing. Even more
    there are several utility functions for data handling and management.
  license_family: GPL3
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
