travis:
  secure:
    BINSTAR_TOKEN: oQhrZOoGnPdb2edipx/3oq9BQLl7jh19c7URLYRUbg3EQpxZdUXRxa3C8FuRiJTshe81iEBHZdDPRsMjxswJnAmzeocR7gQO97EpBkF1mlbet/uigsWruljbQUviJg1zTFntx3F9cEtu9hDABrl+Lxhp/ujv1jDXuRmj5n/pssT3fK3i/U2W87QtcyYzNZtbF8kaOiVFKhL6wTsFOg3FaBRnjQHD7ZpJwW2xfmf8d1qZ9xNrxzbXBQ9HPUyKl8Tm66vHz1yHiYrO0VkqEmdyoWWjI6K2F2YOa6bpMvgh7jt6vggXWpsTU8uorUNrUSkza1Fh1B0fxM7v5lu5FUml/dUXw/5bad9JNh1qqn/8YB1jbBwLN6qLmYZUXRHwu981X6aMhB628PCZ3nAq4jZPpNWcqexR5rETqaCP1hDBX0oGifA+mLjTXFebKK0HyOP+YFlQBKof9qPfra/FS7w0jRK+obnO930pcrwRkXA3CSG5HwRmjIG7vTNIdRVQTM7apbC2Wl35X0+hrZidDHysc3wcboe9p3tAuKT7yv73mr5txdGtRPv/EEV9cNWGnjWAqZQd266SPBcy1Jt5ZOj/80s2w23uvOhkP/2ONVyOKaqSqyW5HEwDWmCDYe/6K9Y5wrWlkmRj9Y1Ej5SzyyZnJaYKHn5v6kk1vxHFx3RO2Kc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
