travis:
  secure:
    BINSTAR_TOKEN: wI1N3aT8aRwIAWBwoBkNYehDSFfVpx+BGwmkVeQd9tzUNf1WSX8uWyCgGS53MdkCjG8ZIonrY5zmiKYkTRKPaMLVmC3JVpQtDawLVbYTteX3DXPazrCaIm0A3ZWcH/cLxpkyx2HLCPXyjZfhScRCtLlrI7/FePpUDwPGo75auA3DOe8aXwNxyrjpTgat3tv1K9L7IhWo4JfwFIfIv0FUrWfGCPTelCAUULatIbibEmYNQPEU9dGHpvfrSLkeCDTbSVFuOh88xgmH4/ipDsT09k/C6YzPbpZFpfNNZtK3syhvfnOxuFHCWUg09YOVCRDzivZywCwjoE8rZ2sftsbT+bToIsw6+396FHg5pOSuFUe8up7MpGQKPaWlC3Fy1frza8qGhjUtVcRyC/P805QruHu629Vw3B4d1ANTRJ91aCs7NA8oxqGx3WNQmZj7+hX73DZwBuPoWLXQbeKP6z8BK9DBUIOFAfb9Vc/YdoWGmQkT2kKUDlmKi4vzas1oVoSGTC735SmxrwNurs/gS7cnvkygk8ZchWlHc+9rgBc9rQ9+Dk1bMR2R8BGEnItW48BY36lQxqRrouLqNctuc/4YKNMOl8uEwyTHph7H8Gln7VrPdBYrejfYDxbDsWRzltmbodItvPe21HYNNS6KjUXtQBfKUPoAZNRdxN8Q9KIlue0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
